apiVersion: batch/v1
kind: Job
metadata:
  name: neobank-db-init
  namespace: neotropolis
  labels:
    app: neobank
    component: db-init
spec:
  ttlSecondsAfterFinished: 300  # Clean up job after 5 minutes
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: neobank
        component: db-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: neobank:latest  # Replace with your actual image registry
        command: ["python", "/app/init_db.py"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neobank-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
